The HTML and CSS files from the past project
KIsmoilov/review-past-project pull request #1
Opened 2022-09-26 14:36 UTC by KIsmoilov

The HTML and CSS files from the past project

2022-09-26 14:57 UTC, KIsmoilov commented on styles.css
> +}
It is nice using id for the image in styling. But, could you please use the "#" hash symbol to your "image" id in your stylesheet? Otherwise, the changes will not reflect.

2022-09-26 15:11 UTC, KIsmoilov reviewed
# STATUS: Required Changes ♻️

You did a great job!

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️
✅  You did a great job by using a separate stylesheet for CSS, but please use CSS selectors correctly. Please review my inline comments below and submit them for re-review when you fixed them. 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻

Happy coding! 👍

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 16:09 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] you did a great job by adding the inline comments but make sure you add the descriptive summary for your review so that the student will directly know if it is the required change, optional change, or invalid pull request. Please Watch this [video with an example](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d) it will help you to know how to make a summary of your review  :grinning: :grinning: :grinning: 

## example of the good summary 
 
```
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-26 16:09 UTC, MaganaAsiati commented on index.html
> +      <h1 id="title">Dr. Norman Borlaug</h1>
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why", for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

2022-09-26 16:09 UTC, MaganaAsiati commented on index.html
> +      <a href="" id="tribute-link" target="_blank">More about Dr. Norman</a>
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why", for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

2022-09-26 16:09 UTC, MaganaAsiati commented on styles.css
> +}
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why", for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

2022-09-26 16:09 UTC, MaganaAsiati commented on styles.css
> +}
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why", for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

2022-09-28 02:57 UTC, mgmediaweb commented on styles.css
> +}
Kindly, I suggest you explain the "why" of your comment and be more explicit with the possible solution

2022-09-28 02:57 UTC, mgmediaweb commented on styles.css
> +}
Kindly, I suggest you explain the "why" of your comment and be more explicit with the possible solution

2022-09-28 02:57 UTC, mgmediaweb commented on index.html
> +      <a href="" id="tribute-link" target="_blank">More about Dr. Norman</a>
Kindly, I suggest you explain the "why" of your comment and be more explicit with the possible solution

2022-09-28 02:57 UTC, mgmediaweb commented on index.html
> +      <h1 id="title">Dr. Norman Borlaug</h1>
Kindly, I suggest you explain the "why" of your comment and be more explicit with the possible solution

2022-09-28 03:00 UTC, mgmediaweb requested changes
Hi @KIsmoilov , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost2](https://user-images.githubusercontent.com/41912912/192677599-052d109a-26f5-4f5a-86ee-b09616ef40c1.gif)

 ## Highlights 💯 
- I appreciate your effort, you can do it! ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 03:26 UTC, KIsmoilov commented on index.html
> +      <h1 id="title">Dr. Norman Borlaug</h1>
It would be great if you can use the "header" semantic tag for your h1 title.
Why?
Using semantic tags is considered as Html best practices.
Possible solution:
<header>
<h1 id="title"> Dr. Norman Borlaug</h1>
</header>

2022-09-28 03:30 UTC, KIsmoilov commented on styles.css
> +}
It is better to give class or id to the element in Html and use them in styling. 
**Why?**
The reason is that there could be other img elements in the Html document 
**Possible solution**

In HTML 
&gt;&lt;img class="photo"

In CSS
.photo {
...
}

2022-09-28 04:06 UTC, emmiiorji approved these changes
Hi @KIsmoilov, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/192240174-571c5ac8-a43f-49b5-9dd0-65acdf152c73.gif)

## Good Highlights✔

- Good use of inline comments
- Review comments are polite
- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 04:14 UTC, merged